version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: eventos-db
    restart: always
    environment:
      POSTGRES_DB: eventos
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
